
package ui;

import game.Dice;
import game.Game;
import game.Player;
import javax.swing.Timer;

public class MainWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainWindow.class.getName());
    
    private Timer diceTimer;
    private int animationStep;
    private int finalRoll;
    private Game game;
    private Dice dice;
    private Player currentPlayer;
    private int currentRollCount;
    private int maxRollsPerPlayer;
    private Timer pauseTimer;
    private Player player1;
    private Player player2;
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        spnDice = new javax.swing.JSpinner();
        btnPlay = new javax.swing.JButton();
        txtPlayer1 = new javax.swing.JTextField();
        txtPlayer2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dice Roller Game");
        setResizable(false);

        mainPanel.setPreferredSize(new java.awt.Dimension(500, 400));

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/dice.png"))); // NOI18N
        jLabel1.setText(" DICE ROLLER GAME");

        jLabel3.setFont(new java.awt.Font("JetBrains Mono", 0, 16)); // NOI18N
        jLabel3.setText("Player 1:");

        jLabel4.setFont(new java.awt.Font("JetBrains Mono", 0, 16)); // NOI18N
        jLabel4.setText("Player 2:");

        jLabel2.setFont(new java.awt.Font("JetBrains Mono", 0, 16)); // NOI18N
        jLabel2.setText("Number of dice:");

        spnDice.setFont(new java.awt.Font("JetBrains Mono", 0, 16)); // NOI18N
        spnDice.setModel(new javax.swing.SpinnerNumberModel(3, 1, 10, 1));

        btnPlay.setFont(new java.awt.Font("JetBrains Mono", 0, 16)); // NOI18N
        btnPlay.setText("PLAY");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        txtPlayer1.setFont(new java.awt.Font("JetBrains Mono", 0, 16)); // NOI18N

        txtPlayer2.setFont(new java.awt.Font("JetBrains Mono", 0, 16)); // NOI18N

        txtOutput.setColumns(20);
        txtOutput.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        txtOutput.setRows(5);
        jScrollPane2.setViewportView(txtOutput);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(spnDice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(mainPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtPlayer1))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spnDice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnPlay)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed

        String player1Name = txtPlayer1.getText();
        String player2Name = txtPlayer2.getText();
        int numberOfDice = (int) spnDice.getValue();

        player1 = new Player(player1Name);
        player2 = new Player(player2Name);
        dice = new Dice();

        txtOutput.setText("");
        txtOutput.append("----- DICE ROLLER GAME -----\n");
        txtOutput.append("Player 1: " + player1Name + "\n");
        txtOutput.append("Player 2: " + player2Name + "\n");
        txtOutput.append("Number of dice: " + numberOfDice +"\n");
        txtOutput.append("---------------------------\n\n");

        game = new Game(player1, player2, dice, numberOfDice, txtOutput);
        maxRollsPerPlayer = numberOfDice;
        currentRollCount = 0;
        currentPlayer = player1;
        startTurn();
    }//GEN-LAST:event_btnPlayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainWindow().setVisible(true));
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JSpinner spnDice;
    private javax.swing.JTextArea txtOutput;
    private javax.swing.JTextField txtPlayer1;
    private javax.swing.JTextField txtPlayer2;
    // End of variables declaration//GEN-END:variables

    public String getDiceAscii(int value) {

        String dice = "";

        String dice1 = """
        -------
        |     |
        |  o  |
        |     |
        -------
        """;

        String dice2 = """
        -------
        | o   |
        |     |
        |   o |
        -------
        """;

        String dice3 = """
        -------
        | o   |
        |  o  |
        |   o |
        -------
        """;

        String dice4 = """
        -------
        | o o |
        |     |
        | o o |
        -------
        """;

        String dice5 = """
        -------
        | o o |
        |  o  |
        | o o |
        -------
        """;

        String dice6 = """
        -------
        | o o |
        | o o |
        | o o |
        -------
        """;

        switch (value) {
            case 1 -> dice = dice1;
            case 2 -> dice = dice2;
            case 3 -> dice = dice3;
            case 4 -> dice = dice4;
            case 5 -> dice = dice5;
            case 6 -> dice = dice6;
            default -> dice = "";
        }
        return dice;
    }
    
    private void animateDiceRoll(Dice dice) {
        animationStep = 0;
        int maxSteps = 5; 

        diceTimer = new Timer(180, e -> {
            animationStep++;
            int tempRoll = (int)(Math.random() * 6) + 1;
            txtOutput.append(getDiceAscii(tempRoll) + "\n");
            
            if (animationStep >= maxSteps) {
                diceTimer.stop();
                finalRoll = dice.roll();
                txtOutput.append(getDiceAscii(finalRoll) + "\n");
                int roll = finalRoll;
                currentPlayer.addToScore(roll);
                txtOutput.append(currentPlayer.getName() + " rolled: [" + roll + "]\n");
                currentRollCount++;
                pauseTimer = new Timer(2000, ev -> {
                    pauseTimer.stop();

                    if (currentRollCount < maxRollsPerPlayer) {
                        animateDiceRoll(dice);
                    } else {
                        txtOutput.append("\nTotal score for " + currentPlayer.getName() + ": " + currentPlayer.getScore() + "\n");
                        if (currentPlayer == player1) {
                            currentPlayer = player2;
                            startTurn();
                        } else if (currentPlayer == player2) {
                            showFinalResult();
                        }
                    }
                });
                pauseTimer.start();
            }
        });
            diceTimer.start();
    }
    
    private void startTurn() {
        txtOutput.append("\n--- Turn: ["+ currentPlayer.getName() + "] ---\n");
        txtOutput.append("Rolling the dice for "+ currentPlayer.getName() +"...\n");
        currentRollCount = 0;
        animateDiceRoll(dice);
        
    }

    private void showFinalResult() {
        txtOutput.append("\n===== END OF GAME =====\n");
        txtOutput.append("FINAL SCORES:\n");
        txtOutput.append(player1.getName() + ": [" + player1.getScore() + "]\n");
        txtOutput.append(player2.getName() + ": [" + player2.getScore() + "]\n");

        if (player1.getScore() > player2.getScore()) {
            txtOutput.append("\n🏆 Winner: " + player1.getName() + "\n");
        } else if (player2.getScore() > player1.getScore()) {
            txtOutput.append("\n🏆 Winner: " + player2.getName() + "\n");
        } else {
            txtOutput.append("\nIt's a tie!\n");
        }
        txtOutput.append("=======================\n");

        currentRollCount = 0;
        currentPlayer = null;
    }
}
